server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookManagement?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    cache: false
    mode: HTML5
